# Generated by Django 4.2.18 on 2025-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note_type', models.CharField(choices=[('public', 'Public'), ('archive', 'Archive')], max_length=10)),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study')], max_length=10)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning')], max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
